// Treatment database seed data
// Based on agricultural extension resources and PlantVillage dataset

export interface TreatmentData {
  name: string;
  type: 'organic' | 'chemical';
  description: string;
  applicationMethod: string;
  dosage: string;
  frequency?: string;
  precautions: string[];
  effectiveness: 'low' | 'medium' | 'high';
  costLevel?: 'low' | 'medium' | 'high';
}

export interface DiseaseData {
  name: string;
  scientificName?: string;
  description: string;
  symptoms: string[];
  causes?: string;
  prevention?: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  isHealthy: boolean;
  treatments: TreatmentData[];
}

export interface CropData {
  name: string;
  scientificName: string;
  category: string;
  description: string;
  growingTips?: string;
  diseases: DiseaseData[];
}

export const SEED_DATA: CropData[] = [
  {
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    category: 'Vegetable',
    description: 'One of the most widely grown vegetables, susceptible to various fungal and viral diseases.',
    growingTips: 'Needs full sun, regular watering, and support for vines. Avoid overhead watering to prevent disease.',
    diseases: [
      {
        name: 'Healthy',
        description: 'The plant shows no signs of disease and is in optimal condition.',
        symptoms: ['Vibrant green leaves', 'Strong stems', 'Normal fruit development'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Early Blight',
        scientificName: 'Alternaria solani',
        description: 'Fungal disease causing dark spots with concentric rings on leaves.',
        symptoms: [
          'Dark brown spots with concentric rings',
          'Yellowing around spots',
          'Lower leaves affected first',
          'Leaf drop',
        ],
        causes: 'Fungus spreads through infected plant debris and water splash.',
        prevention: 'Crop rotation, mulching, avoid overhead watering, remove infected leaves.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Neem Oil Spray',
            type: 'organic',
            description: 'Natural fungicide from neem tree seeds',
            applicationMethod: 'Spray on affected leaves, covering both surfaces',
            dosage: '2-4 tablespoons per gallon of water',
            frequency: 'Every 7-14 days',
            precautions: ['Avoid spraying in direct sunlight', 'Test on small area first'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Copper Fungicide',
            type: 'organic',
            description: 'Copper-based spray for fungal prevention',
            applicationMethod: 'Apply as preventive spray or at first signs',
            dosage: '1-4 tablespoons per gallon per label',
            frequency: 'Weekly during wet conditions',
            precautions: ['Can build up in soil', 'Avoid during hot weather'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
          {
            name: 'Chlorothalonil',
            type: 'chemical',
            description: 'Broad-spectrum contact fungicide',
            applicationMethod: 'Spray every 7-10 days during disease pressure',
            dosage: 'Follow manufacturer label',
            frequency: 'Every 7-10 days',
            precautions: [
              'Wear protective equipment',
              'Keep away from water sources',
              'Observe pre-harvest interval',
            ],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Late Blight',
        scientificName: 'Phytophthora infestans',
        description: 'Devastating disease that caused the Irish Potato Famine. Spreads rapidly in cool, wet conditions.',
        symptoms: [
          'Water-soaked lesions on leaves',
          'White fuzzy growth on leaf undersides',
          'Brown/black blotches on stems',
          'Rapid plant death',
        ],
        causes: 'Oomycete pathogen thrives in cool, humid conditions.',
        prevention: 'Plant resistant varieties, ensure air circulation, avoid overhead irrigation.',
        severity: 'critical',
        isHealthy: false,
        treatments: [
          {
            name: 'Remove Infected Plants',
            type: 'organic',
            description: 'Immediately remove and destroy infected plants',
            applicationMethod: 'Bag and dispose of infected material, do not compost',
            dosage: 'N/A',
            precautions: ['Do not compost infected material', 'Sanitize tools'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Copper Hydroxide',
            type: 'organic',
            description: 'Preventive copper fungicide',
            applicationMethod: 'Apply before disease appears or at first sign',
            dosage: 'Per label instructions',
            frequency: 'Every 5-7 days during wet weather',
            precautions: ['Apply before rain', 'Reapply after heavy rain'],
            effectiveness: 'medium',
            costLevel: 'medium',
          },
          {
            name: 'Mefenoxam + Chlorothalonil',
            type: 'chemical',
            description: 'Systemic plus contact fungicide combination',
            applicationMethod: 'Spray at first sign of disease',
            dosage: 'Per manufacturer instructions',
            frequency: 'Every 7-14 days',
            precautions: [
              'Rotate with other fungicides',
              'PPE required',
              'Follow label intervals',
            ],
            effectiveness: 'high',
            costLevel: 'high',
          },
        ],
      },
      {
        name: 'Bacterial Spot',
        scientificName: 'Xanthomonas campestris',
        description: 'Bacterial disease causing leaf spots and fruit lesions.',
        symptoms: [
          'Small, dark, water-soaked spots',
          'Spots may have yellow halos',
          'Raised scabby spots on fruit',
          'Leaf distortion',
        ],
        causes: 'Bacteria spread by water splash, infected seeds, and transplants.',
        prevention: 'Use disease-free seeds, avoid overhead watering, crop rotation.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Copper-based Bactericide',
            type: 'organic',
            description: 'Copper compounds for bacterial control',
            applicationMethod: 'Apply at first sign of disease',
            dosage: 'Per label recommendations',
            frequency: 'Every 7-10 days',
            precautions: ['May cause phytotoxicity in hot weather', 'Limit applications'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Streptomycin',
            type: 'chemical',
            description: 'Antibiotic for bacterial diseases',
            applicationMethod: 'Spray at transplanting and early growth',
            dosage: 'Per label',
            frequency: 'Every 5-7 days during infection period',
            precautions: [
              'Resistance can develop',
              'Not for use near harvest',
              'Check local regulations',
            ],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Leaf Mold',
        scientificName: 'Passalora fulva',
        description: 'Fungal disease primarily affecting greenhouse tomatoes.',
        symptoms: [
          'Pale green to yellow spots on upper leaf',
          'Olive-green to brown velvety growth on underside',
          'Leaves curl and drop',
        ],
        causes: 'High humidity and poor air circulation.',
        prevention: 'Improve ventilation, reduce humidity, resistant varieties.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Improve Ventilation',
            type: 'organic',
            description: 'Increase airflow around plants',
            applicationMethod: 'Prune lower leaves, space plants wider',
            dosage: 'N/A',
            precautions: ['Sanitize pruning tools'],
            effectiveness: 'high',
            costLevel: 'low',
          },
          {
            name: 'Potassium Bicarbonate',
            type: 'organic',
            description: 'Contact fungicide safe for food crops',
            applicationMethod: 'Spray on affected foliage',
            dosage: '1-2 tablespoons per gallon',
            frequency: 'Weekly',
            precautions: ['May require repeat applications'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
        ],
      },
      {
        name: 'Septoria Leaf Spot',
        scientificName: 'Septoria lycopersici',
        description: 'Common fungal disease causing numerous small spots on leaves.',
        symptoms: [
          'Small circular spots with dark borders',
          'Tan/gray centers with dark specks',
          'Lower leaves affected first',
          'Severe defoliation possible',
        ],
        causes: 'Fungal spores spread by rain splash and wind.',
        prevention: 'Mulching, crop rotation, avoid overhead watering.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Baking Soda Spray',
            type: 'organic',
            description: 'Home remedy creating unfavorable pH for fungus',
            applicationMethod: 'Spray on leaves weekly',
            dosage: '1 tbsp baking soda + 1 tsp liquid soap per gallon',
            frequency: 'Weekly',
            precautions: ['Too much can harm plants', 'Test first'],
            effectiveness: 'low',
            costLevel: 'low',
          },
          {
            name: 'Chlorothalonil',
            type: 'chemical',
            description: 'Protective fungicide',
            applicationMethod: 'Apply before disease appears or at first sign',
            dosage: 'Per label',
            frequency: 'Every 7-14 days',
            precautions: ['Wear PPE', 'Follow pre-harvest interval'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Yellow Leaf Curl Virus',
        scientificName: 'Tomato yellow leaf curl virus (TYLCV)',
        description: 'Viral disease transmitted by whiteflies causing severe yield loss.',
        symptoms: [
          'Upward curling of leaf margins',
          'Yellowing of leaves',
          'Stunted growth',
          'Reduced fruit production',
        ],
        causes: 'Transmitted by silverleaf whitefly (Bemisia tabaci).',
        prevention: 'Control whiteflies, use reflective mulches, plant resistant varieties.',
        severity: 'high',
        isHealthy: false,
        treatments: [
          {
            name: 'Whitefly Control - Insecticidal Soap',
            type: 'organic',
            description: 'Control vector to prevent spread',
            applicationMethod: 'Spray on whitefly populations',
            dosage: 'Per label, usually 2% solution',
            frequency: 'Every 5-7 days',
            precautions: ['Direct contact required', 'May need multiple applications'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Remove Infected Plants',
            type: 'organic',
            description: 'No cure exists - remove infected plants',
            applicationMethod: 'Remove and destroy infected plants promptly',
            dosage: 'N/A',
            precautions: ['Bag before removing to avoid spreading whiteflies'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Imidacloprid',
            type: 'chemical',
            description: 'Systemic insecticide for whitefly control',
            applicationMethod: 'Soil drench or foliar spray',
            dosage: 'Per label instructions',
            frequency: 'As needed for whitefly control',
            precautions: [
              'Toxic to bees - avoid bloom time',
              'Systemic residues',
              'Follow label restrictions',
            ],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Apple',
    scientificName: 'Malus domestica',
    category: 'Fruit',
    description: 'Popular fruit tree susceptible to scab, fire blight, and cedar apple rust.',
    growingTips: 'Requires winter chill hours. Prune annually for best production and disease prevention.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Tree shows no signs of disease with healthy foliage and fruit.',
        symptoms: ['Clean, green leaves', 'No spots or lesions', 'Normal fruit development'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Apple Scab',
        scientificName: 'Venturia inaequalis',
        description: 'Most common apple disease causing olive-colored spots on leaves and fruit.',
        symptoms: [
          'Olive-green velvety spots on leaves',
          'Spots turn brown and may crack',
          'Scabby lesions on fruit',
          'Premature leaf drop',
        ],
        causes: 'Fungus overwinters in fallen leaves, spreads in spring rains.',
        prevention: 'Remove fallen leaves, plant resistant varieties, proper spacing.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Sulfur Spray',
            type: 'organic',
            description: 'Traditional fungicide for scab prevention',
            applicationMethod: 'Apply from green tip through petal fall',
            dosage: 'Per label, usually lime-sulfur or wettable sulfur',
            frequency: 'Every 7-10 days during wet spring',
            precautions: ['Do not use with oil sprays', 'Can cause russeting'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Captan',
            type: 'chemical',
            description: 'Protectant fungicide for scab',
            applicationMethod: 'Apply on 7-10 day schedule',
            dosage: 'Per label instructions',
            frequency: 'Every 7-10 days',
            precautions: ['Avoid application near harvest', 'PPE required'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Black Rot',
        scientificName: 'Botryosphaeria obtusa',
        description: 'Fungal disease affecting leaves, fruit, and branches.',
        symptoms: [
          'Frogeye leaf spots (tan centers, purple margins)',
          'Black rotting on fruit',
          'Cankers on branches',
          'Mummified fruit',
        ],
        causes: 'Fungus overwinters in mummified fruit and cankers.',
        prevention: 'Remove mummies and cankers, improve air circulation.',
        severity: 'high',
        isHealthy: false,
        treatments: [
          {
            name: 'Sanitation',
            type: 'organic',
            description: 'Remove and destroy infected material',
            applicationMethod: 'Prune cankers 6-8 inches below visible infection',
            dosage: 'N/A',
            precautions: ['Sterilize tools between cuts', 'Destroy prunings'],
            effectiveness: 'high',
            costLevel: 'low',
          },
          {
            name: 'Captan + Myclobutanil',
            type: 'chemical',
            description: 'Combination of protectant and systemic fungicide',
            applicationMethod: 'Apply during primary infection period',
            dosage: 'Per label',
            frequency: 'Every 10-14 days',
            precautions: ['Follow all label directions', 'Observe PHI'],
            effectiveness: 'high',
            costLevel: 'high',
          },
        ],
      },
      {
        name: 'Cedar Apple Rust',
        scientificName: 'Gymnosporangium juniperi-virginianae',
        description: 'Rust disease requiring both apple and juniper hosts to complete life cycle.',
        symptoms: [
          'Bright orange spots on leaves',
          'Spots develop tube-like projections underneath',
          'Fruit may show raised rings',
          'Premature defoliation',
        ],
        causes: 'Fungus alternates between apple and juniper/cedar hosts.',
        prevention: 'Remove nearby junipers within 500ft if possible, plant resistant varieties.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Remove Juniper Galls',
            type: 'organic',
            description: 'Break the disease cycle by removing galls from nearby junipers',
            applicationMethod: 'Remove orange gelatinous galls from junipers in early spring',
            dosage: 'N/A',
            precautions: ['Must be done before spore release'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Myclobutanil',
            type: 'chemical',
            description: 'Systemic fungicide effective against rusts',
            applicationMethod: 'Apply from pink bud through cover sprays',
            dosage: 'Per label',
            frequency: 'Every 7-14 days during infection period',
            precautions: ['Resistance management important', 'Follow label'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Potato',
    scientificName: 'Solanum tuberosum',
    category: 'Vegetable',
    description: 'Important staple crop susceptible to early and late blight.',
    growingTips: 'Plant in well-drained soil, hill soil around stems, avoid wet conditions.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Plant is disease-free with normal growth.',
        symptoms: ['Healthy green foliage', 'Strong stems', 'Normal tuber development'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Early Blight',
        scientificName: 'Alternaria solani',
        description: 'Fungal disease similar to tomato early blight.',
        symptoms: [
          'Brown spots with concentric rings (target spots)',
          'Lower leaves affected first',
          'Yellowing and leaf drop',
        ],
        causes: 'Same pathogen as tomato early blight.',
        prevention: 'Crop rotation (3+ years), certified seed, adequate fertility.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Copper Fungicide',
            type: 'organic',
            description: 'Preventive spray for early blight',
            applicationMethod: 'Apply before symptoms appear',
            dosage: 'Per label',
            frequency: 'Every 7-10 days',
            precautions: ['Avoid excessive applications'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Azoxystrobin',
            type: 'chemical',
            description: 'Strobilurin fungicide with protectant and curative activity',
            applicationMethod: 'Apply at first sign or preventively',
            dosage: 'Per label instructions',
            frequency: 'Every 7-14 days',
            precautions: ['Rotate with other modes of action', 'Follow PHI'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Late Blight',
        scientificName: 'Phytophthora infestans',
        description: 'The disease that caused the Irish Potato Famine - highly destructive.',
        symptoms: [
          'Water-soaked lesions on leaves',
          'White mold on leaf undersides',
          'Stem lesions',
          'Rapid plant death in cool, wet weather',
        ],
        causes: 'Oomycete spreads rapidly in cool, humid conditions.',
        prevention: 'Plant certified seed, destroy cull piles, monitor weather forecasts.',
        severity: 'critical',
        isHealthy: false,
        treatments: [
          {
            name: 'Destroy Infected Plants',
            type: 'organic',
            description: 'Remove infected plants immediately',
            applicationMethod: 'Bag and remove, vine kill before harvest if infected',
            dosage: 'N/A',
            precautions: ['Do not compost', 'Clean equipment'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Cymoxanil + Mancozeb',
            type: 'chemical',
            description: 'Curative and protectant combination',
            applicationMethod: 'Apply at first detection',
            dosage: 'Per label',
            frequency: 'Every 5-7 days during outbreaks',
            precautions: ['Wear full PPE', 'Mandatory under some regulations'],
            effectiveness: 'high',
            costLevel: 'high',
          },
        ],
      },
    ],
  },
  {
    name: 'Grape',
    scientificName: 'Vitis vinifera',
    category: 'Fruit',
    description: 'Vine crop used for wine, juice, and fresh eating. Susceptible to various fungal diseases.',
    growingTips: 'Good air circulation essential. Train vines properly and prune annually.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Vines are disease-free with healthy growth.',
        symptoms: ['Green leaves', 'Proper fruit set', 'No spots or lesions'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Black Rot',
        scientificName: 'Guignardia bidwellii',
        description: 'Devastating fungal disease that can destroy entire grape crop.',
        symptoms: [
          'Tan spots with dark borders on leaves',
          'Fruit turns brown, shrivels to hard mummies',
          'Black pycnidia visible on mummies',
        ],
        causes: 'Fungus overwinters in mummified fruit.',
        prevention: 'Remove all mummies, good canopy management, sanitation.',
        severity: 'high',
        isHealthy: false,
        treatments: [
          {
            name: 'Mummy Removal',
            type: 'organic',
            description: 'Remove and destroy all mummified fruit',
            applicationMethod: 'Collect and burn or bury deeply',
            dosage: 'N/A',
            frequency: 'Before bud break',
            precautions: ['Must remove all mummies'],
            effectiveness: 'high',
            costLevel: 'low',
          },
          {
            name: 'Mancozeb',
            type: 'chemical',
            description: 'Protectant fungicide',
            applicationMethod: 'Apply from early shoot growth through veraison',
            dosage: 'Per label',
            frequency: 'Every 7-14 days',
            precautions: ['66-day PHI', 'Wear PPE'],
            effectiveness: 'high',
            costLevel: 'low',
          },
        ],
      },
      {
        name: 'Esca (Black Measles)',
        scientificName: 'Phaeomoniella chlamydospora complex',
        description: 'Complex trunk disease affecting mature vines.',
        symptoms: [
          'Tiger stripe pattern on leaves',
          'Dark spotting on berries',
          'Vine decline and death',
          'Internal wood necrosis',
        ],
        causes: 'Multiple fungi colonizing wood, enters through pruning wounds.',
        prevention: 'Delay pruning until late winter, protect wounds, avoid stress.',
        severity: 'high',
        isHealthy: false,
        treatments: [
          {
            name: 'Pruning Wound Protection',
            type: 'organic',
            description: 'Apply wound sealant after pruning',
            applicationMethod: 'Paint or spray on fresh pruning cuts',
            dosage: 'Cover wound completely',
            precautions: ['Apply immediately after pruning'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Trunk Renewal',
            type: 'organic',
            description: 'Train new trunk from sucker',
            applicationMethod: 'Select healthy sucker and train as replacement trunk',
            dosage: 'N/A',
            precautions: ['Multi-year process'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Leaf Blight',
        scientificName: 'Isariopsis leaf spot',
        description: 'Fungal disease causing necrotic lesions on leaves.',
        symptoms: [
          'Irregular brown spots',
          'Necrotic areas on leaves',
          'Premature defoliation',
        ],
        causes: 'Fungal pathogen favored by humid conditions.',
        prevention: 'Good air circulation, remove infected leaves.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Improve Canopy Management',
            type: 'organic',
            description: 'Open canopy to improve air flow',
            applicationMethod: 'Leaf pulling and shoot positioning',
            dosage: 'N/A',
            precautions: ['Avoid excessive leaf removal'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Copper Spray',
            type: 'organic',
            description: 'Copper fungicide application',
            applicationMethod: 'Apply during growing season',
            dosage: 'Per label',
            frequency: 'Every 10-14 days',
            precautions: ['Can accumulate in vineyard soils'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
        ],
      },
    ],
  },
  {
    name: 'Corn (Maize)',
    scientificName: 'Zea mays',
    category: 'Grain',
    description: 'Major grain crop susceptible to various foliar diseases.',
    growingTips: 'Plant in blocks for pollination. Needs full sun and consistent moisture.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Plants are healthy with normal development.',
        symptoms: ['Green leaves', 'Strong stalks', 'Normal ear development'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Northern Leaf Blight',
        scientificName: 'Exserohilum turcicum',
        description: 'Major foliar disease of corn in temperate regions.',
        symptoms: [
          'Long, elliptical gray-green lesions',
          'Lesions can be 1-6 inches long',
          'May coalesce and kill leaves',
        ],
        causes: 'Fungus survives on corn debris, favored by moderate temperatures and humidity.',
        prevention: 'Resistant hybrids, crop rotation, residue management.',
        severity: 'high',
        isHealthy: false,
        treatments: [
          {
            name: 'Crop Rotation',
            type: 'organic',
            description: 'Rotate to non-host crops',
            applicationMethod: 'Plant soybeans or other non-grass crops',
            dosage: 'At least 1 year rotation',
            precautions: ['Check neighboring fields for inoculum'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Azoxystrobin + Propiconazole',
            type: 'chemical',
            description: 'Combination fungicide for foliar diseases',
            applicationMethod: 'Apply at tasseling if disease present',
            dosage: 'Per label',
            frequency: 'Usually single application',
            precautions: ['Economics depend on yield potential and disease pressure'],
            effectiveness: 'high',
            costLevel: 'high',
          },
        ],
      },
      {
        name: 'Common Rust',
        scientificName: 'Puccinia sorghi',
        description: 'Rust disease common in sweet corn and dent corn.',
        symptoms: [
          'Reddish-brown pustules on both leaf surfaces',
          'Pustules burst releasing spores',
          'Severe infection causes yellowing',
        ],
        causes: 'Spores blown in from southern regions, cannot overwinter in cold climates.',
        prevention: 'Resistant varieties, early planting.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Resistant Varieties',
            type: 'organic',
            description: 'Plant rust-resistant hybrids',
            applicationMethod: 'Select at planting time',
            dosage: 'N/A',
            precautions: ['Check regional disease pressure'],
            effectiveness: 'high',
            costLevel: 'low',
          },
          {
            name: 'Propiconazole',
            type: 'chemical',
            description: 'Triazole fungicide for rust control',
            applicationMethod: 'Apply when rust first appears',
            dosage: 'Per label',
            frequency: 'May need repeat application',
            precautions: ['Timing is critical', 'Follow PHI'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Cercospora Leaf Spot',
        scientificName: 'Cercospora zeae-maydis',
        description: 'Gray leaf spot - serious disease in humid regions.',
        symptoms: [
          'Rectangular gray lesions parallel to veins',
          'Lesions have sharp, linear margins',
          'Can coalesce killing entire leaves',
        ],
        causes: 'Fungus survives in crop residue, favors extended leaf wetness.',
        prevention: 'Resistant hybrids, tillage of residue, crop rotation.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Residue Management',
            type: 'organic',
            description: 'Bury or decompose corn residue',
            applicationMethod: 'Tillage or rotation to accelerate breakdown',
            dosage: 'N/A',
            precautions: ['Balance with soil conservation needs'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Trifloxystrobin',
            type: 'chemical',
            description: 'Strobilurin fungicide',
            applicationMethod: 'Apply at VT-R1 growth stage',
            dosage: 'Per label',
            frequency: 'Usually single application',
            precautions: ['Apply before severe infection'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Pumpkin',
    scientificName: 'Cucurbita maxima',
    category: 'Vegetable',
    description:
      'Winter squash group widely grown for fruit; cucurbit foliage is prone to powdery mildew, downy mildew, and bacterial spots.',
    growingTips:
      'Full sun, fertile well-drained soil, space for vines. Avoid overhead watering on leaves; mulch to reduce soil splash.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Vines and leaves show normal color and vigor with no pathogen symptoms.',
        symptoms: ['Deep green leaves', 'Normal vine growth', 'No spots or mold on foliage'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Powdery Mildew',
        scientificName: 'Podosphaera xanthii / Erysiphe cichoracearum',
        description: 'White powdery patches on leaves that can spread and weaken the plant.',
        symptoms: ['White talcum-like spots on upper leaves', 'Leaves may curl or yellow', 'Late-season defoliation'],
        causes: 'Airborne fungal spores favor warm days and cool nights with moderate humidity.',
        prevention: 'Resistant varieties, adequate spacing, remove heavily infected leaves early.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Sulfur Spray',
            type: 'organic',
            description: 'Protectant fungicide effective against powdery mildew',
            applicationMethod: 'Cover leaf surfaces before infection spreads',
            dosage: 'Per product label for cucurbits',
            frequency: 'Every 7–14 days when disease pressure is high',
            precautions: ['Do not apply in heat above 90°F', 'Avoid drift to sensitive plants'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Potassium Bicarbonate',
            type: 'organic',
            description: 'Contact treatment that raises leaf surface pH',
            applicationMethod: 'Spray all leaf surfaces at first sign',
            dosage: '2–3 tbsp per gallon (follow label)',
            frequency: 'Every 5–7 days as needed',
            precautions: ['Test on a few leaves first'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Myclobutanil',
            type: 'chemical',
            description: 'Systemic triazole for powdery mildew',
            applicationMethod: 'Apply when disease first appears',
            dosage: 'Per label for cucurbits',
            precautions: ['Observe pre-harvest interval', 'Rotate FRAC groups'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Downy Mildew',
        scientificName: 'Pseudoperonospora cubensis',
        description: 'Oomycete disease causing angular yellow lesions and fuzzy growth on leaf undersides.',
        symptoms: [
          'Yellow angular patches on upper leaf surface',
          'Dark spores on underside in humid weather',
          'Leaves can brown and die',
        ],
        causes: 'Wind-dispersed spores; favors wet leaves and cool nights.',
        prevention: 'Rotate cucurbits, drip irrigation, wider row spacing for airflow.',
        severity: 'high',
        isHealthy: false,
        treatments: [
          {
            name: 'Copper Fungicide',
            type: 'organic',
            description: 'Protectant spray to limit spread',
            applicationMethod: 'Apply before forecasts of prolonged wet weather',
            dosage: 'Per label',
            frequency: '7–10 day intervals during outbreaks',
            precautions: ['Phytotoxicity on some cultivars—test first'],
            effectiveness: 'medium',
            costLevel: 'medium',
          },
          {
            name: 'Mefenoxam + Chlorothalonil',
            type: 'chemical',
            description: 'Common combination for cucurbit downy mildew (check local labels)',
            applicationMethod: 'Begin at first detection or high regional risk',
            dosage: 'Per label',
            precautions: ['Resistance management—alternate modes of action'],
            effectiveness: 'high',
            costLevel: 'high',
          },
        ],
      },
      {
        name: 'Bacterial Leaf Spot',
        scientificName: 'Xanthomonas campestris / Pseudomonas spp.',
        description: 'Small water-soaked spots that become tan or brown with possible yellow halos.',
        symptoms: ['Tiny angular spots following leaf veins', 'Shot-hole appearance', 'Dark streaks on stems under wet conditions'],
        causes: 'Bacteria spread by rain splash, tools, and contaminated seed.',
        prevention: 'Use certified seed, avoid working wet foliage, sanitize tools.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Copper Hydroxide',
            type: 'organic',
            description: 'Copper bactericide to slow spread',
            applicationMethod: 'Spray at first symptoms',
            dosage: 'Per label',
            frequency: 'Every 5–7 days while wet weather persists',
            precautions: ['Excessive copper harms soil life—use judiciously'],
            effectiveness: 'medium',
            costLevel: 'medium',
          },
          {
            name: 'Streptomycin (where legal)',
            type: 'chemical',
            description: 'Antibiotic spray where registered for agricultural use',
            applicationMethod: 'Only where permitted by local regulation',
            dosage: 'Per label',
            precautions: ['Resistance risk—use as part of IPM', 'Check legality in your region'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
      {
        name: 'Anthracnose',
        scientificName: 'Colletotrichum spp.',
        description: 'Dark sunken lesions on leaves, stems, and fruit under warm wet conditions.',
        symptoms: ['Circular tan/brown leaf spots', 'Sunken lesions on fruit', 'Stem cankers on runners'],
        causes: 'Fungus survives in crop debris; spreads with splashing water.',
        prevention: 'Deep crop rotation, destroy residues, drip irrigation.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Remove Infected Fruit and Leaves',
            type: 'organic',
            description: 'Sanitation to reduce inoculum',
            applicationMethod: 'Bag and discard diseased tissue; do not compost',
            dosage: 'N/A',
            precautions: ['Disinfect pruners between plants'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Chlorothalonil',
            type: 'chemical',
            description: 'Multi-site protectant fungicide',
            applicationMethod: 'Apply on a protectant schedule during warm wet periods',
            dosage: 'Per label',
            precautions: ['Protect pollinators—timing matters'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Strawberry',
    scientificName: 'Fragaria × ananassa',
    category: 'Fruit',
    description: 'Popular berry crop susceptible to fungal leaf diseases, especially in humid climates.',
    growingTips: 'Plant in well-drained soil with full sun. Avoid overhead irrigation and ensure good air circulation between rows.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Plant is in optimal condition with no signs of disease.',
        symptoms: ['Bright green leaves', 'Strong runners', 'Normal fruit set'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Leaf Scorch',
        scientificName: 'Diplocarpon earlianum',
        description: 'Fungal disease causing small purple-to-brown spots that merge and give leaves a scorched appearance.',
        symptoms: ['Small dark purple spots on upper leaf surface', 'Spots enlarge and coalesce', 'Leaf margins turn brown and dry', 'Severe infection causes defoliation'],
        causes: 'Fungal spores spread by rain splash and wind. Favored by warm wet weather.',
        prevention: 'Use certified disease-free plants, remove old foliage after harvest, avoid overhead irrigation.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Captan Fungicide',
            type: 'organic',
            description: 'Broad-spectrum protectant fungicide effective against leaf scorch',
            applicationMethod: 'Spray upper and lower leaf surfaces thoroughly',
            dosage: '2 lb per acre or per product label',
            frequency: 'Every 7–10 days during wet weather',
            precautions: ['Do not apply near water sources', 'Wear protective gear'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
          {
            name: 'Remove Infected Leaves',
            type: 'organic',
            description: 'Sanitation to reduce fungal inoculum in the planting',
            applicationMethod: 'Hand-remove and destroy visibly infected leaves',
            dosage: 'N/A',
            frequency: 'Weekly during growing season',
            precautions: ['Bag and discard — do not compost infected material'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Myclobutanil',
            type: 'chemical',
            description: 'Systemic triazole fungicide for leaf scorch control',
            applicationMethod: 'Apply at first sign of disease, cover all foliage',
            dosage: 'Per label for strawberry',
            frequency: 'Every 10–14 days, max applications per season per label',
            precautions: ['Observe pre-harvest interval', 'Rotate fungicide groups'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Cherry',
    scientificName: 'Prunus avium',
    category: 'Fruit',
    description: 'Stone fruit tree valued for sweet or tart fruit, prone to powdery mildew in warm dry conditions.',
    growingTips: 'Plant in well-drained, fertile soil. Prune to open canopy for airflow. Avoid excess nitrogen.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Tree is vigorous with no signs of disease.',
        symptoms: ['Glossy dark green leaves', 'Normal shoot growth', 'Clean fruit set'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Powdery Mildew',
        scientificName: 'Podosphaera clandestina',
        description: 'Fungal disease producing white powdery growth on young leaves, shoots, and fruit.',
        symptoms: ['White powdery coating on young leaves', 'Curling and distortion of new growth', 'Premature leaf drop', 'Russeting on fruit surface'],
        causes: 'Airborne fungal spores thrive in warm dry days with cool humid nights. Shade and dense canopy worsen outbreaks.',
        prevention: 'Prune for open canopy, avoid excess nitrogen fertilization, plant resistant varieties.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Sulfur Spray',
            type: 'organic',
            description: 'Contact fungicide effective against powdery mildew on cherry',
            applicationMethod: 'Spray all young foliage and shoot tips at first sign',
            dosage: 'Per product label',
            frequency: 'Every 7–14 days while conditions favor disease',
            precautions: ['Do not apply within 2 weeks of oil sprays', 'Avoid applying above 90°F'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Neem Oil',
            type: 'organic',
            description: 'Botanical oil that disrupts fungal growth',
            applicationMethod: 'Apply to all foliage surfaces in early morning or evening',
            dosage: '2 tbsp per gallon water with emulsifier',
            frequency: 'Every 7 days preventively',
            precautions: ['Do not apply in direct sunlight', 'Avoid when bees are active'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Tebuconazole',
            type: 'chemical',
            description: 'Systemic triazole fungicide for powdery mildew on stone fruits',
            applicationMethod: 'Apply from pre-bloom through cover sprays',
            dosage: 'Per label for cherry',
            frequency: '14-day intervals, per label limits',
            precautions: ['Observe pre-harvest interval', 'Highly toxic to aquatic organisms'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Orange',
    scientificName: 'Citrus sinensis',
    category: 'Fruit',
    description: 'Major citrus crop; Huanglongbing (citrus greening) is the most devastating disease with no cure.',
    growingTips: 'Requires well-drained soil, full sun, and protection from frost. Monitor regularly for Asian citrus psyllid.',
    diseases: [
      {
        name: 'Citrus Greening',
        scientificName: 'Candidatus Liberibacter asiaticus',
        description: 'Deadly bacterial disease spread by the Asian citrus psyllid insect. There is no cure — infected trees must be removed.',
        symptoms: ['Yellow mottling on leaves (asymmetric, unlike nutrient deficiency)', 'Lopsided, bitter, green fruit that stays green at bottom', 'Premature fruit drop', 'Twig dieback', 'Tree decline over 1–5 years'],
        causes: 'Bacteria transmitted by Asian citrus psyllid (Diaphorina citri). Can also spread via infected grafting material.',
        prevention: 'Control psyllid populations with insecticides, use certified disease-free nursery stock, remove and destroy infected trees immediately.',
        severity: 'critical',
        isHealthy: false,
        treatments: [
          {
            name: 'Psyllid Control — Horticultural Oil',
            type: 'organic',
            description: 'Suffocate psyllid nymphs and eggs to slow disease spread to healthy trees',
            applicationMethod: 'Spray new flush growth where psyllids lay eggs',
            dosage: '1–2% oil solution',
            frequency: 'At each new flush flush emergence',
            precautions: ['Do not apply in heat above 90°F', 'Ineffective as standalone control for advanced infection'],
            effectiveness: 'medium',
            costLevel: 'low',
          },
          {
            name: 'Remove Infected Trees',
            type: 'organic',
            description: 'Infected trees cannot be cured — removal prevents spread to surrounding healthy trees',
            applicationMethod: 'Cut down and immediately chip or burn infected trees',
            dosage: 'N/A',
            precautions: ['Notify local agricultural authorities', 'Treat stumps to prevent regrowth'],
            effectiveness: 'high',
            costLevel: 'low',
          },
          {
            name: 'Imidacloprid (Systemic Psyllid Control)',
            type: 'chemical',
            description: 'Systemic insecticide applied to soil or trunk to kill psyllid vectors and slow spread',
            applicationMethod: 'Soil drench or trunk injection per product label',
            dosage: 'Per label for citrus',
            frequency: 'Annually or per label',
            precautions: ['Highly toxic to bees — do not apply during bloom', 'Does not cure infected trees'],
            effectiveness: 'medium',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Peach',
    scientificName: 'Prunus persica',
    category: 'Fruit',
    description: 'Stone fruit tree widely grown in temperate climates. Bacterial spot is a major limiting disease.',
    growingTips: 'Needs winter chilling, well-drained soil, and full sun. Prune annually for airflow and light penetration.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Tree shows vigorous growth with no disease symptoms.',
        symptoms: ['Bright green leaves without spots', 'Normal shoot elongation', 'Clean unblemished fruit'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Bacterial Spot',
        scientificName: 'Xanthomonas arboricola pv. pruni',
        description: 'Bacterial disease causing spots on leaves, fruit, and twigs leading to defoliation and fruit blemishes.',
        symptoms: ['Small water-soaked spots on leaves that turn purple-brown', 'Shot-hole appearance as spot centers fall out', 'Fruit pitting and cracking', 'Twig cankers in severe cases'],
        causes: 'Bacteria overwinter in twig cankers. Spread by rain splash during warm wet springs.',
        prevention: 'Plant resistant varieties, apply copper sprays preventively, avoid overhead irrigation.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Copper Hydroxide',
            type: 'organic',
            description: 'Copper bactericide applied preventively from pink bud through shuck split',
            applicationMethod: 'Spray all surfaces at delayed dormant through petal fall',
            dosage: 'Per label for stone fruits',
            frequency: 'Every 5–7 days in wet weather',
            precautions: ['Excess copper causes phytotoxicity on peach — do not over-apply', 'Not effective after infection occurs'],
            effectiveness: 'medium',
            costLevel: 'medium',
          },
          {
            name: 'Kaolin Clay',
            type: 'organic',
            description: 'Particle film that deters bacterial spread and insect vectors',
            applicationMethod: 'Apply as film spray on young leaves and fruit',
            dosage: '25 kg per 1000 L water',
            frequency: 'Reapply after rain',
            precautions: ['Rinse fruit before eating', 'Does not replace fungicide program'],
            effectiveness: 'low',
            costLevel: 'low',
          },
          {
            name: 'Oxytetracycline',
            type: 'chemical',
            description: 'Antibiotic bactericide registered for bacterial spot on stone fruits in many regions',
            applicationMethod: 'Apply at full pink through shuck split',
            dosage: 'Per label',
            frequency: '5–7 day intervals during wet weather',
            precautions: ['Check local registration', 'Resistance risk — rotate with copper'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Bell Pepper',
    scientificName: 'Capsicum annuum',
    category: 'Vegetable',
    description: 'Warm-season vegetable; bacterial spot is the primary foliar disease in humid conditions.',
    growingTips: 'Needs warm soil, full sun, and consistent moisture. Stake plants for support and avoid overhead watering.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Plant is growing vigorously with no disease symptoms.',
        symptoms: ['Dark green glossy leaves', 'Upright sturdy stems', 'Normal flower and fruit development'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
      {
        name: 'Bacterial Spot',
        scientificName: 'Xanthomonas euvesicatoria',
        description: 'Bacterial disease causing water-soaked spots on leaves and fruit that reduce yield and quality.',
        symptoms: ['Small water-soaked circular spots on leaves', 'Spots turn brown with yellow halo', 'Raised scab-like lesions on fruit', 'Severe defoliation in wet seasons'],
        causes: 'Bacteria spread by rain, irrigation splash, insects, and contaminated tools. Warm wet weather accelerates spread.',
        prevention: 'Use certified disease-free seed, copper sprays preventively, rotate crops, avoid overhead irrigation.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Copper-based Bactericide',
            type: 'organic',
            description: 'Protectant copper spray to limit bacterial spread',
            applicationMethod: 'Begin sprays before expected wet weather or at first symptoms',
            dosage: 'Per product label for peppers',
            frequency: 'Every 5–7 days during warm wet weather',
            precautions: ['Phytotoxicity possible with repeated applications', 'Spray in early morning'],
            effectiveness: 'medium',
            costLevel: 'medium',
          },
          {
            name: 'Remove Infected Tissue',
            type: 'organic',
            description: 'Prune heavily infected leaves to reduce bacterial load',
            applicationMethod: 'Cut and bag infected leaves, disinfect pruners between plants',
            dosage: 'N/A',
            frequency: 'As needed throughout season',
            precautions: ['Work when foliage is dry to avoid spreading bacteria'],
            effectiveness: 'low',
            costLevel: 'low',
          },
          {
            name: 'Acibenzolar-S-methyl (Actigard)',
            type: 'chemical',
            description: 'Plant activator that induces systemic acquired resistance against bacterial spot',
            applicationMethod: 'Apply as foliar spray starting early in season',
            dosage: 'Per label (typically 0.5–1 oz/acre)',
            frequency: 'Every 7–10 days, per label limits',
            precautions: ['Works best preventively, not after heavy infection', 'Tank-mix with copper for best results'],
            effectiveness: 'high',
            costLevel: 'high',
          },
        ],
      },
    ],
  },
  {
    name: 'Squash',
    scientificName: 'Cucurbita',
    category: 'Vegetable',
    description: 'Cucurbit vegetable highly susceptible to powdery mildew, especially in late summer.',
    growingTips: 'Plant in full sun with generous spacing. Drip irrigation keeps foliage dry. Remove heavily infected leaves early.',
    diseases: [
      {
        name: 'Powdery Mildew',
        scientificName: 'Podosphaera xanthii',
        description: 'Very common fungal disease producing white powdery colonies on leaves that reduce photosynthesis and yield.',
        symptoms: ['White talcum-like patches on upper leaf surface', 'Yellowing of affected areas', 'Premature leaf senescence', 'Reduced fruit size and quality'],
        causes: 'Airborne spores; unusually favored by moderate humidity without free water on leaves. Warm days and cool nights accelerate spread.',
        prevention: 'Resistant varieties, adequate plant spacing, avoid excess nitrogen, remove infected leaves.',
        severity: 'medium',
        isHealthy: false,
        treatments: [
          {
            name: 'Baking Soda Spray',
            type: 'organic',
            description: 'Raises surface pH to inhibit fungal spore germination',
            applicationMethod: 'Spray upper and lower leaf surfaces thoroughly',
            dosage: '1 tbsp baking soda + 1 tsp horticultural oil per gallon water',
            frequency: 'Every 7 days at first signs',
            precautions: ['Can cause leaf burn if too concentrated', 'Reapply after rain'],
            effectiveness: 'low',
            costLevel: 'low',
          },
          {
            name: 'Sulfur Dust or Spray',
            type: 'organic',
            description: 'Protectant fungicide highly effective against cucurbit powdery mildew',
            applicationMethod: 'Dust or spray all leaf surfaces before colonies establish',
            dosage: 'Per product label',
            frequency: 'Every 7–10 days during disease pressure',
            precautions: ['Do not apply above 90°F', 'Keep away from eyes and skin'],
            effectiveness: 'high',
            costLevel: 'low',
          },
          {
            name: 'Trifloxystrobin',
            type: 'chemical',
            description: 'Strobilurin fungicide with curative and protectant activity on powdery mildew',
            applicationMethod: 'Apply at first detection of disease',
            dosage: 'Per label for cucurbits',
            frequency: '14-day intervals, per label limits',
            precautions: ['Rotate with non-strobilurin fungicides', 'Resistance developing in some regions'],
            effectiveness: 'high',
            costLevel: 'medium',
          },
        ],
      },
    ],
  },
  {
    name: 'Blueberry',
    scientificName: 'Vaccinium corymbosum',
    category: 'Fruit',
    description: 'Acid-soil berry crop. Healthy plants require correct soil pH (4.5–5.5) and good drainage.',
    growingTips: 'Acidify soil if needed, mulch with pine bark, prune out old canes annually. Avoid waterlogging.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Plant is thriving with correct soil conditions and no disease pressure.',
        symptoms: ['Deep green leaves', 'Strong new cane growth', 'Normal fruit development and ripening'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
    ],
  },
  {
    name: 'Raspberry',
    scientificName: 'Rubus idaeus',
    category: 'Fruit',
    description: 'Cane fruit that produces abundantly when managed well. Prone to several fungal and viral diseases.',
    growingTips: 'Support canes on trellis, remove old floricanes after harvest, ensure good air circulation.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Canes and leaves show normal vigor with no disease symptoms.',
        symptoms: ['Green upright canes', 'Normal leaf color without spots', 'Good fruit set'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
    ],
  },
  {
    name: 'Soybean',
    scientificName: 'Glycine max',
    category: 'Legume',
    description: 'Major oilseed and protein crop. Healthy plants fix atmospheric nitrogen when inoculated with Bradyrhizobium.',
    growingTips: 'Inoculate seed with rhizobium, ensure proper pH (6.0–6.8), rotate with non-legume crops.',
    diseases: [
      {
        name: 'Healthy',
        description: 'Crop is growing normally with active nitrogen fixation and no foliar disease.',
        symptoms: ['Dark green trifoliate leaves', 'Visible root nodules', 'Normal pod development'],
        severity: 'low',
        isHealthy: true,
        treatments: [],
      },
    ],
  },
];

// Function to get all crops
export function getAllCrops(): CropData[] {
  return SEED_DATA;
}

// Function to get crop by name
export function getCropByName(name: string): CropData | undefined {
  return SEED_DATA.find(crop => crop.name.toLowerCase() === name.toLowerCase());
}

// Function to get diseases for a crop
export function getDiseasesForCrop(cropName: string): DiseaseData[] {
  const crop = getCropByName(cropName);
  return crop?.diseases || [];
}

// Function to get treatments for a disease
export function getTreatmentsForDisease(cropName: string, diseaseName: string): TreatmentData[] {
  const diseases = getDiseasesForCrop(cropName);
  const disease = diseases.find(d => d.name.toLowerCase() === diseaseName.toLowerCase());
  return disease?.treatments || [];
}
