import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'crops',
      columns: [
        { name: 'name', type: 'string', isIndexed: true },
        { name: 'scientific_name', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'image_uri', type: 'string', isOptional: true },
        { name: 'model_class_id', type: 'number', isIndexed: true },
        { name: 'growing_tips', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'diseases',
      columns: [
        { name: 'crop_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string', isIndexed: true },
        { name: 'scientific_name', type: 'string', isOptional: true },
        { name: 'description', type: 'string' },
        { name: 'symptoms', type: 'string' },
        { name: 'causes', type: 'string', isOptional: true },
        { name: 'prevention', type: 'string', isOptional: true },
        { name: 'severity', type: 'string' },
        { name: 'image_uri', type: 'string', isOptional: true },
        { name: 'model_class_id', type: 'number', isIndexed: true },
        { name: 'is_healthy', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'treatments',
      columns: [
        { name: 'disease_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'application_method', type: 'string' },
        { name: 'dosage', type: 'string' },
        { name: 'frequency', type: 'string', isOptional: true },
        { name: 'precautions', type: 'string' },
        { name: 'effectiveness', type: 'string' },
        { name: 'cost_level', type: 'string', isOptional: true },
        { name: 'availability', type: 'string', isOptional: true },
        { name: 'environmental_impact', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'scan_history',
      columns: [
        { name: 'image_uri', type: 'string' },
        { name: 'crop_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'disease_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'crop_name', type: 'string', isOptional: true },
        { name: 'disease_name', type: 'string', isOptional: true },
        { name: 'crop_confidence', type: 'number' },
        { name: 'disease_confidence', type: 'number' },
        { name: 'is_healthy', type: 'boolean' },
        { name: 'latitude', type: 'number', isOptional: true },
        { name: 'longitude', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'scanned_at', type: 'number', isIndexed: true },
      ],
    }),
  ],
});
